from parse_chapter import get_chapter_objs
import ebooklib
from ebooklib import epub
from bs4 import BeautifulSoup

invalid_speaker_list = [
    "Sedai"
]
valid_context_list = [
    "said",
    "shouted",
    "gave",
    "tucked",
    "addressed",
    "muttered",
    "floated",
    "ripped",
    "twitched",
    "fastened",
    "bowed",
    "brushed",
    "hunched",
    "prided",
    "regarded",
    "accompanied",
    "climbed",
    "clapped",
    "fastened",
    "dusted",
    "emptied",
    "joined",
    "grabbed",
    "channeled",
    "fumbled",
    "squirmed",
    "buried",
    "hated",
    "nudged",
    "walked",
    "joined",
    "wiggled",
    "snagged",
    "mounted",
    "vaulted",
    "stalked",
    "stabbed",
    "flowed",
    "cut",
    "took",
    "mutter","muttered",
    "voice","voiced",
    "snap","snapped",
    "cut","cutted",
    "murmur","murmured",
    "muse","mused",
    "command","commanded",
    "whisper","whispered",
    "snarle","snarled",
    "ask","asked",
    "sneer","sneered",
    "growl","growled",
    "hitch","hitched",
    "began",
    "heel","heeled",
    "call", "called",
    "told",
    "wince","winced",
    "burst",
    "protest","protested",
    "open","opened",
    "shook",
    "chuckle","chuckled",
    "add","added",
    "answer","answered",
    "could",
    "indicate", "indicated",
    "nod", "nodded",
    "sighed",
    "rose", "lifted", "dropped",
    "showed",
    "straightened",
    "made",
    "smiled",
    "blink","blinked",
    "stopped",
    "drew","drawing",
    "moved","moving",
    "spun","spinning",
    "examined",
    "gesture","gestured",
    "study","studied",
    "started",
    "wormed",
    "managed",
    "took",
    "relaxed",
    "pointed",
    "explained",
    "seemed",
    "grimmaced",
    "shrugged",
    "ignored",
    "became",
    "glanced",
    "exclaimed",
    "patted",
    "shivered",
    "turned",
    "rolled",
    "grimaced",
    "shifted",
    "groaned",
    "looked",
    "hesitated",
    "thought",
    "grunted",
    "rubbed",
    "waved",
    "snorted",
    "laughed",
    "scrambled",
    "leaned",
    "clawed",
    "rasped",
    "shouted",
    "stared",
    "frowned",
    "knew",
    "had",
    "noticed"
    "pulled",
    "hissed",
    "paused",
    "limped",
    "reached",
    "did",
    "repeated",
    "stepped",
    "insisted",
    "breathed",
    "sat",
    "scrubbed",
    "smoothed",
    "swung",
    "announced",
    "quoted",
    "noticed",
    "peered",
    "rounded",
    "cleared",
    "let",
    "regained",
    "demanded",
    "appeared",
    "stood",
    "cleared",
    "dashed",
    "tested",
    "tasted",
    "went",
    "yawned",
    "pushed",
    "bobbed",
    "demanded",
    "rumbled",
    "caught",
    "sounded",
    "trailed",
    "darted",
    "finished",
    "replied",
    "bound",
    "waited",
    "shut",
    "barked",
    "pounded",
    "sounded",
    "swallowed",
    "trailed",
    "gasped",
    "raised",
    "went",
    "replied",
    "felt",
    "held",
    "tried",
    "who",
    "should",
    "grated",
    "jerked",
    "hung",
    "fought",
    "ran",
    "held",
    "stared",
    "pulled",
    "closed",
    "inhaled",
    "lengthened",
    "pushing",
    "kept",
    "led",
    "put",
    "eyed",
    "sending",
    "bristled",
    "stumbled",
    "capped",
    "eyed",
    "tapped",
    "considered",
    "squeaked",
    "gaped",
    "wondered",
    "blurted",
    "tugged",
    "admonished",
    "tilted",
    "rushed",
    "sniffed",
    "listened",
    "plucked",
    "exchanged",
    "mumbled",
    "realized",
    "spread",
    "fell",
    "skittered",
    "dug",
    "reined",
    "motioned",
    "gathered",
    "whirled",
    "clasped",
    "dismissed",
    "found",
    "surprised",
    "followed",
    "hurried",
    "curtsied",
    "glared",
    "returned",
    "assured",
    "tossed",
    "felled",
    "curtsied",
    "stretched",
    "slipped",
    "scowled",
    "maintained",
    "wished",
    "remembered",
    "mouthed",
    "shocked",
    "arched",
    "rummaged",
    "clutched",
    "intoned",
    "panted",
    "trembled",
    "forced",
    "sank",
    "burned",
    "intoned",
    "shuddered",
    "proclaimed",
    "assulted",
    "cried",
    "strode",
    "observed",
    "sobbed",
    "roared",
    "snatched",
    "grabbed"
    "scrabbled",
    "gripped",
    "agreed",
    "embraced",
    "hoped",
    "fingered",
    "annihilated",
    "moaned",
    "threw",
    "blushed",
    "continued",
    "snickered",
    "produced",
    "passed",
    "touched",
    "stiffened",
    "adjusted",
    "released",
    "strummed",
    "abandoned",
    "bellowed",
    "choked",
    "recieved",
    "winked",
    "shuddered",
    "huddled",
    "agreed",
    "bandaged",
    "washed",
    "ducked",
    "blinked",
    "tightened",
    "continued",
    "wiped",
    "nodded",
    "shuddered",
    "slapped",
    "twisted",
    "recognized",
    "worked",
    "picked",
    "stooped",
    "struggled",
    "dodged",
    "squatted",
    "agreed",
    "glowered",
    "spoke",
    "yelped",
    "rode",
    "lowered",
    "roared",
    "jumped",
    "twisted",
    "giggled",
    "squinted",
    "grinned",
    "checked",
    "retrieved",
    "delivered",
    "clamped",
    "snatched",
    "touched",
    "refused",
    "knocked",
    "settled",
    "schooled",
    "focused",
    "agreed",
    "allowed",
    "mimicked",
    "doubted",
    "flashed",
    "threw",
    "hit",
    "jumped",
    "twisted",
    "stuffed",
    "glowered",
    "described",
    "wove",
    "cried",
    "came",
    "leaped",
    "froze",
    "dumped",
    "removed",
    "left",
    "watched",
    "set",
    "nodded",
    "spoiled",
    "booted",
    "stationed",
    "paused",
    "howled",
    "pronounced",
    "assaulted",
    "crooned",
    "flinched",
    "scrabbled",
    "expected",
    "stuck",
    "chose",
    "slicked",
    "handed",
    "pressed",
    "received",
    "slammed",
    "seized",
    "stifled",
    "vanished",
    "cursed",
    "admitted",
    "veiled",
    "formed",
    "plunged"]
same_speaker_tokens = [
    "his",
    "he",
    "it",
    "its",
    "she",
    "her",
    "we",
    "they"]

def parse_epub_to_chapters(epub_path):
    """
    Parse an EPUB file into an array of chapters.
    
    Args:
        epub_path (str): Path to the EPUB file
        
    Returns:
        list: Array of chapter texts
    """
    try:
        book = epub.read_epub(epub_path)
        chapters = []
        
        for item in book.get_items():
            if item.get_type() == ebooklib.ITEM_DOCUMENT:
                # Extract text content from HTML
                txt = BeautifulSoup(
                    item.get_content().decode('utf-8')
                    .replace(u"\xa0","")
                    .replace(u"\u2019","'")
                    .replace(u"\u201c",'\t"')
                    .replace(u"\u2014"," - ")
                    .replace(u"\u2026","...")
                    .replace(u"\u201d",'"')
                    .replace(u"\u2018","'")
                    .replace(u"\u2013","-")
                    # spaces
                    .replace(u"\u0009","") # character tabulation
                    .replace(u"\u000A","\n") # line feed
                    .replace(u"\u000B"," ") # line tabulation
                    .replace(u"\u000C"," ") # form feed
                    .replace(u"\u000D","\n") # carriage return
                    .replace(u"\u0020"," ") # space
                    .replace(u"\u0085","\n") # next line
                    .replace(u"\u00A0"," ") # no-break space
                    .replace(u"\u1680"," ") # ogham space mark
                    .replace(u"\u180E"," ") # mongolian vowel separator
                    .replace(u"\u2000"," ") # en quad
                    .replace(u"\u2001"," ") # em quad
                    .replace(u"\u2002"," ") # en space
                    .replace(u"\u2004"," ") # three-per-em space
                    .replace(u"\u2005"," ") # four-per-em space
                    .replace(u"\u2006"," ") # six-per-em space
                    .replace(u"\u2007"," ") # figure space
                    .replace(u"\u2008"," ") # punctuation space
                    .replace(u"\u2009"," ") # thin space
                    .replace(u"\u200A"," ") # hair space
                    .replace(u"\u200B"," ") # zero width space
                    .replace(u"\u200C"," ") # zero width non-joiner
                    .replace(u"\u200D"," ") # zero width joiner
                    .replace(u"\u2028","\n ") # line separator
                    .replace(u"\u2029","\n\n") # paragraph separator
                    .replace(u"\u202F"," ") # narrow no-break space
                    .replace(u"\u205F"," ") # medium mathematical space
                    .replace(u"\u2060","-") # word joiner
                    .replace(u"\u3000"," ") # ideographic space
                    .encode('ascii')
                    , 'html.parser').get_text(separator=" ", strip=False)
                if txt.strip():  # Only add non-empty chapters
                    chapters.append(get_chapter_objs(txt))
        return chapters
    
    except Exception as e:
        print(f"Error parsing EPUB file: {e}")
        return []