#!/usr/bin/env python3
"""
Module to parse chapter content and return chapter objects.
"""
import ebooklib
from ebooklib import epub
from bs4 import BeautifulSoup

invalid_speaker_list = [
    "Sedai",
    "Light",
    "Dust",
    "I",
    "Aiel",
    "Ogier",
    "Ripples",
    "Ajah",
    "A",
    "The",
    "And",
    "Valon",
    "This",
    "Ones",
    "One",
    "Tower",
    "Most",
    "What",
    "Next",
    "Source",
    "Else",
    "Andor",
    "For",
    "Something",
    "Reborn",
    "Another",
    "Weeping",
    "Novices",
    "Ive",
    "Last",
    "Earth",
    "Pain",
    "Women",
    "Laughter",
    "Mayene",
    "Why",
    "Horn",
    "Those",
    "Darkness",
    "That",
    "Cairhienin",
    "Halfman",
    "Circle",
    "People",
    "Just",
    "Byir",
    "Some",
    "Shadow",
    "Thus",
    "Others",
    "Forsaken",
    "There",
    "Stone",
    'Amyrlin',
    'Each',
    'Rivers',
    'Weeds',
    'Ajahs',
    'Road',
    'Someone',
    'Remember',
    'Blood',
    'Eagle',
    'Emotion',
    'Whites',
    'Man',
    'Folk',
    'Miere',
    'Anger',
    'No',
    'Prophecy',
    'Spear',
    'Guilt',
    'Younglings',
    'Tears',
    'Waygate',
    'So',
    'Whoever',
    'Everyone',
    'Who',
    'Both',
    'No',
    'Talking',
    'Tinker',
    'Power',
    'Companions',
    'Panarch',
    'Lords',
    'Shield',
    'Taardad',
    'Where',
    'Commiseration',
    'Legends',
    'Suspicion',
    'Bowstrings',
    'Maidens',
    'Tinkers',
    'Oaths',
    'Rage',
    'Or',
    'Nothing',
    'Rhuidean',
    'Neither',
    'How',
    'Hill',
    'Two',
    'Tairens',
    'But',
    'Tell',
    'Sweat',
    'Ill',
    'Stepper',
    'Forkbeard',
    'Jindo',
    'Shaido'
]
valid_context_list = [
    "said",
    "shouted",
    "gave",
    "tucked",
    "addressed",
    "muttered",
    "floated",
    "ripped",
    "twitched",
    "fastened",
    "bowed",
    "brushed",
    "hunched",
    "prided",
    "regarded",
    "accompanied",
    "climbed",
    "clapped",
    "fastened",
    "dusted",
    "emptied",
    "joined",
    "grabbed",
    "channeled",
    "fumbled",
    "squirmed",
    "buried",
    "hated",
    "nudged",
    "walked",
    "joined",
    "wiggled",
    "snagged",
    "mounted",
    "vaulted",
    "stalked",
    "stabbed",
    "flowed",
    "cut",
    "took",
    "mutter","muttered",
    "voice","voiced",
    "snap","snapped",
    "cut","cutted",
    "murmur","murmured",
    "muse","mused",
    "command","commanded",
    "whisper","whispered",
    "snarle","snarled",
    "ask","asked",
    "sneer","sneered",
    "growl","growled",
    "hitch","hitched",
    "began",
    "heel","heeled",
    "call", "called",
    "told",
    "wince","winced",
    "burst",
    "protest","protested",
    "open","opened",
    "shook",
    "chuckle","chuckled",
    "add","added",
    "answer","answered",
    "could",
    "indicate", "indicated",
    "nod", "nodded",
    "sighed",
    "rose", "lifted", "dropped",
    "showed",
    "straightened",
    "made",
    "smiled",
    "blink","blinked",
    "stopped",
    "drew","drawing",
    "moved","moving",
    "spun","spinning",
    "examined",
    "gesture","gestured",
    "study","studied",
    "started",
    "wormed",
    "managed",
    "took",
    "relaxed",
    "pointed",
    "explained",
    "seemed",
    "grimmaced",
    "shrugged",
    "ignored",
    "became",
    "glanced",
    "exclaimed",
    "patted",
    "shivered",
    "turned",
    "rolled",
    "grimaced",
    "shifted",
    "groaned",
    "looked",
    "hesitated",
    "thought",
    "grunted",
    "rubbed",
    "waved",
    "snorted",
    "laughed",
    "scrambled",
    "leaned",
    "clawed",
    "rasped",
    "shouted",
    "stared",
    "frowned",
    "knew",
    "had",
    "noticed"
    "pulled",
    "hissed",
    "paused",
    "limped",
    "reached",
    "did",
    "repeated",
    "stepped",
    "insisted",
    "breathed",
    "sat",
    "scrubbed",
    "smoothed",
    "swung",
    "announced",
    "quoted",
    "noticed",
    "peered",
    "rounded",
    "cleared",
    "let",
    "regained",
    "demanded",
    "appeared",
    "stood",
    "cleared",
    "dashed",
    "tested",
    "tasted",
    "went",
    "yawned",
    "pushed",
    "bobbed",
    "demanded",
    "rumbled",
    "caught",
    "sounded",
    "trailed",
    "darted",
    "finished",
    "replied",
    "bound",
    "waited",
    "shut",
    "barked",
    "pounded",
    "sounded",
    "swallowed",
    "trailed",
    "gasped",
    "raised",
    "went",
    "replied",
    "felt",
    "held",
    "tried",
    "who",
    "should",
    "grated",
    "jerked",
    "hung",
    "fought",
    "ran",
    "held",
    "stared",
    "pulled",
    "closed",
    "inhaled",
    "lengthened",
    "pushing",
    "kept",
    "led",
    "put",
    "eyed",
    "sending",
    "bristled",
    "stumbled",
    "capped",
    "eyed",
    "tapped",
    "considered",
    "squeaked",
    "gaped",
    "wondered",
    "blurted",
    "tugged",
    "admonished",
    "tilted",
    "rushed",
    "sniffed",
    "listened",
    "plucked",
    "exchanged",
    "mumbled",
    "realized",
    "spread",
    "fell",
    "skittered",
    "dug",
    "reined",
    "motioned",
    "gathered",
    "whirled",
    "clasped",
    "dismissed",
    "found",
    "surprised",
    "followed",
    "hurried",
    "curtsied",
    "glared",
    "returned",
    "assured",
    "tossed",
    "felled",
    "curtsied",
    "stretched",
    "slipped",
    "scowled",
    "maintained",
    "wished",
    "remembered",
    "mouthed",
    "shocked",
    "arched",
    "rummaged",
    "clutched",
    "intoned",
    "panted",
    "trembled",
    "forced",
    "sank",
    "burned",
    "intoned",
    "shuddered",
    "proclaimed",
    "assulted",
    "cried",
    "strode",
    "observed",
    "sobbed",
    "roared",
    "snatched",
    "grabbed"
    "scrabbled",
    "gripped",
    "agreed",
    "embraced",
    "hoped",
    "fingered",
    "annihilated",
    "moaned",
    "threw",
    "blushed",
    "continued",
    "snickered",
    "produced",
    "passed",
    "touched",
    "stiffened",
    "adjusted",
    "released",
    "strummed",
    "abandoned",
    "bellowed",
    "choked",
    "recieved",
    "winked",
    "shuddered",
    "huddled",
    "agreed",
    "bandaged",
    "washed",
    "ducked",
    "blinked",
    "tightened",
    "continued",
    "wiped",
    "nodded",
    "shuddered",
    "slapped",
    "twisted",
    "recognized",
    "worked",
    "picked",
    "stooped",
    "struggled",
    "dodged",
    "squatted",
    "agreed",
    "glowered",
    "spoke",
    "yelped",
    "rode",
    "lowered",
    "roared",
    "jumped",
    "twisted",
    "giggled",
    "squinted",
    "grinned",
    "checked",
    "retrieved",
    "delivered",
    "clamped",
    "snatched",
    "touched",
    "refused",
    "knocked",
    "settled",
    "schooled",
    "focused",
    "agreed",
    "allowed",
    "mimicked",
    "doubted",
    "flashed",
    "threw",
    "hit",
    "jumped",
    "twisted",
    "stuffed",
    "glowered",
    "described",
    "wove",
    "cried",
    "came",
    "leaped",
    "froze",
    "dumped",
    "removed",
    "left",
    "watched",
    "set",
    "nodded",
    "spoiled",
    "booted",
    "stationed",
    "paused",
    "howled",
    "pronounced",
    "assaulted",
    "crooned",
    "flinched",
    "scrabbled",
    "expected",
    "stuck",
    "chose",
    "slicked",
    "handed",
    "pressed",
    "received",
    "slammed",
    "seized",
    "stifled",
    "vanished",
    "cursed",
    "admitted",
    "veiled",
    "formed",
    "plunged"]
same_speaker_tokens = [
    "his",
    "he",
    "it",
    "its",
    "she",
    "her",
    "we",
    "they",
    "you"]

speaker_map =dict([
('narrator', 1),
('she', 3),
('Mat', 2),
('Nynaeve', 3),
('Perrin', 2),
('Egwene', 3),
('Thom', 2),
('Elayne', 3),
('Moiraine', 3),
('her', 3),
('Lan', 2),
('Amyrlin', 3),
(None, 1),
('Rand', 2),
('Zarine', 3),
('Verin', 3),
('Loial', 4),
('Min', 3),
('Niall', 2),
('Sheriam', 3),
('Gill', 2),
('Simion', 2),
('Warder', 2),
('Sandar', 2),
('Elaida', 3),
('Carridin', 2),
('Gawyn', 2),
('Myrddraal', 4),
('Galad', 2),
('He', 2),
('Aviendha', 3),
('Baalzamon', 4),
('Masema', 2),
('Rhuarc', 2),
('Chiad', 3),
('Tallanvor', 2),
('Guard', 2),
('Alanna', 3),
('Uno', 2),
('Byar', 2),
('Mallia', 3),
('Ailhuin', 3),
('Ordeith', 4),
('Gaul', 2),
('Hurin', 2),
('Siuan', 3),
('Liandrin', 3),
('Guenna', 3),
('Hopper', 4),
('Selene', 3),
('Orban', 2),
('Shienaran', 2),
('Hammar', 2),
('Accepted', 3),
('Bain', 3),
('Adden', 2),
('Nieda', 3),
('Morgase', 3),
('Belal', 2),
('Daughter-Heir', 3),
('Keeper', 3),
('Inquisitor', 2),
('Ragan', 2),
('Trollocs', 4),
('Furlan', 3),
('Ellisor', 3),
('Aludra', 3),
('Comar', 2),
('Ajala', 2),
('Rianna', 3),
('Whitecloaks', 2),
('Leane', 3),
('Vasa', 2),
('Faolain', 3),
('Beldeine', 3),
('Men', 2),
('Gaebril', 2),
('Haret', 2),
('Commanders', 2),
('Lugard', 2),
('Leya', 3),
('Whitecloak', 2),
('Silvie', 3),
('Lords', 2),
('Merrilin', 2),
('Jolien', 2),
('Tammuz', 2),
('Derne', 2),
('Questioners', 2),
('Shienarans', 2),
('Sweat', 2),
('It', 1),
('Dailin', 2),
('Sharbon', 2),
('Anaiya', 3),
('Serafelle', 3),
('Illianer', 2),
('She', 3),
('Charn', 2),
('Adine', 3),
('Jeadeen', 3),
('Leilwin', 3),
('Gyldin', 3),
('Marillin', 3),
('Bethamin', 3),
('Mahdi', 2),
('Dav', 2),
('Leof', 2),
('Heirn', 2),
('Temaile', 3),
('Moghedien', 4),
('Alviarin', 3),
('Taisa', 3),
('Amico', 3),
('Lini', 3),
('Torean', 2),
('Estanda', 3),
('Saralin', 3,),
('Elisa', 3),
('Rianna', 3),
('Tanchicans', 1),
('Ahan', 2),
('Kenley', 2),
('Sanche', 3),
('Barstere', 2),
('Cenn', 2),
('Luhhan', 2),
('Wil', 2),
('Elam', 2),
('Lian', 3),
('Dannil', 2),
('Joiya', 3),
('Bodewhin', 3),
('Tear', 2),
('Gearan', 2),
('Lugarder', 2),
('Cauthon', 2),
('Wit', 2),
('Daise', 3),
('Rendra', 3),
('Isendre', 3),
('Aielwomen',3), 
('Alsbet', 3),
('Asmodean', 2),
('Sealdre', 3),
('Dowtry', 2),
('Bili', 2),
('Amathera', 3),
('Sahra', 3),
('Pura', 3),
('Alwhin', 3),
('Narisse', 3),
('Mordaine', 2),
('Morin', 2),
('Mayor', 2),
('Keille', 3),
('Asne', 3),
('Jeaine', 3),
('Slayer', 4),
('Coplin', 2),
('Congar', 2),
('Jaim', 2),
('Erim', 2),
('Lanfear', 3),
('Farran', 2),
('Sammael', 2),
('Carleon', 3),
('Charendin', 3),
('Maigran', 3),
('Luca', 2),
('Alijha', 3),
('Someshta', 3),
('Amys', 3),
('Bair', 3),
('Bornhald', 2),
('Tam', 2),
('Egeanin', 3),
('Bran', 2),
('Seana', 3),
('Abell', 2),
('Luc', 2),
('Ila', 3),
('Aielman', 2),
('Couladin', 2),
('Natael', 3),
('Aram', 2),
('Coine', 2),
('Melaine', 3),
('Adan', 2),
('Marin', 3),
('Kadere', 2),
('Juilin', 2),
('Domon', 2),
('Raen', 3),
('Jeordam', 2),
('Lewin', 2),
('Jac', 2),
('Taraboners', 2),
('Warders', 2),
('Flann', 2),
('Baran', 2),
('Reimon', 2),
('Berelain', 3),
('Meilan', 3),
('Laras', 3),
('Mandein', 3),
('Jonai', 3),
('Sunamon', 2),
('Sailmistress', 2),
('Tomada', 2),
('Edorion', 2),
('Ewin', 2),
('Han', 2),
('Solinda', 3),
('Coumin', 3),
('Ihvon', 2),
('Garam', 2),
('Tomas', 2),
('Bael', 2),
('Carlomin', 3),
('Windfinder', 3),
('Eldrith', 3),
('Estean', 3),
('Jorin', 2),
('Charlin', 2),
('Sulwin', 3),
('Gelb', 2),
('Ban', 2),
('Adelin', 3),
('Sevanna', 3),
('Darl', 3),
('Birgitte', 3),
('Jenn', 3),
('Dermon', 3)
])

class ChapterObj:
    def __init__(self, has_quotes: bool, text: str, prev_speaker):
        self.has_quotes = has_quotes
        if self.has_quotes:
            self.speaker = prev_speaker
        else:
            self.speaker = "narrator"
        self.text = text.strip()
    def _get_speaker_num(self):
        if self.has_quotes:
            return 2
        else:
            return 1
    def __str__(self):
        # if self.has_quotes:
        #     return '"' + self.text + '"'
        # else:
        #     return self.text
        #return f"Speaker {self._get_speaker_num()}: {self.text}"
        return f"Speaker {self.get_speaker()}: ({self.get_speaker()})  {self.text}"
    def get_speaker(self):
        # If we have a speaker reference and it's a ChapterObj, resolve it
        if self.speaker is None:
            return self.speaker
        elif isinstance(self.speaker, ChapterObj):
            return self.speaker.get_speaker()
        else:
            return self.speaker
    def set_speaker(self, speaker):
        self.speaker = speaker

def get_chapter_objs(text: str):
    """
    Parse a chapter's text and return a list of chapter objects with the required properties.
    
    Args:
        text (str): The full text of the chapter
        
    Returns:
        list: List of ChapterObj objects with has_quotes, speaker, and text properties
    """
    # Split text into paragraphs (assuming paragraphs are separated by single newlines)
    paragraphs = text.split('\n')
    
    # Create a list of ChapterObj for each paragraph
    chapter_objs = []
    prev_speaker = None # prev_speaker only links between quoted areas
    for paragraph in paragraphs:
        # Skip empty paragraphs
        if paragraph.strip():
            # If there are quotes, we need to split the paragraph to separate the quote from the rest
            if '"' in paragraph:
                # Find all quoted text in the paragraph
                quotes = [x.strip() for x in paragraph.split('"')]
                if paragraph.startswith('"'):
                    quote_en=True
                else:
                    quote_en=False
                for quote in quotes:
                    if len(quote)>0:
                        chapter_objs.append(ChapterObj(quote_en,  quote, prev_speaker))
                        if quote_en:
                            prev_speaker = chapter_objs[-1]
                            
                    quote_en = not quote_en
            else:
                # No quotes, treat as normal paragraph
                chapter_objs.append(ChapterObj(False, paragraph, prev_speaker))
    return chapter_objs

def parse_epub_to_chapters(epub_path):
    """
    Parse an EPUB file into an array of chapters.
    
    Args:
        epub_path (str): Path to the EPUB file
        
    Returns:
        list: Array of chapter texts
    """
    try:
        book = epub.read_epub(epub_path)
        chapters = []
        
        for item in book.get_items():
            if item.get_type() == ebooklib.ITEM_DOCUMENT:
                # Extract text content from HTML
                txt = BeautifulSoup(
                    item.get_content().decode('utf-8')
                    .replace(u"\xa0","")
                    .replace(u"\u2019","'")
                    .replace(u"\u201c",'\t"')
                    .replace(u"\u2014"," - ")
                    .replace(u"\u2026","...")
                    .replace(u"\u201d",'"')
                    .replace(u"\u2018","'")
                    .replace(u"\u2013","-")
                    # spaces
                    .replace(u"\u0009","") # character tabulation
                    .replace(u"\u000A","\n") # line feed
                    .replace(u"\u000B"," ") # line tabulation
                    .replace(u"\u000C"," ") # form feed
                    .replace(u"\u000D","\n") # carriage return
                    .replace(u"\u0020"," ") # space
                    .replace(u"\u0085","\n") # next line
                    .replace(u"\u00A0"," ") # no-break space
                    .replace(u"\u1680"," ") # ogham space mark
                    .replace(u"\u180E"," ") # mongolian vowel separator
                    .replace(u"\u2000"," ") # en quad
                    .replace(u"\u2001"," ") # em quad
                    .replace(u"\u2002"," ") # en space
                    .replace(u"\u2004"," ") # three-per-em space
                    .replace(u"\u2005"," ") # four-per-em space
                    .replace(u"\u2006"," ") # six-per-em space
                    .replace(u"\u2007"," ") # figure space
                    .replace(u"\u2008"," ") # punctuation space
                    .replace(u"\u2009"," ") # thin space
                    .replace(u"\u200A"," ") # hair space
                    .replace(u"\u200B"," ") # zero width space
                    .replace(u"\u200C"," ") # zero width non-joiner
                    .replace(u"\u200D"," ") # zero width joiner
                    .replace(u"\u2028","\n ") # line separator
                    .replace(u"\u2029","\n\n") # paragraph separator
                    .replace(u"\u202F"," ") # narrow no-break space
                    .replace(u"\u205F"," ") # medium mathematical space
                    .replace(u"\u2060","-") # word joiner
                    .replace(u"\u3000"," ") # ideographic space
                    .encode('ascii')
                    , 'html.parser').get_text(separator=" ", strip=False)
                if txt.strip():  # Only add non-empty chapters
                    chapters.append(get_chapter_objs(txt))
        return chapters
    
    except Exception as e:
        print(f"Error parsing EPUB file: {e}")
        return []